Fix an issue with kernel container in some payment modules
PrestaShop/ps_emailalerts pull request #103
Opened 2022-01-31 19:23 UTC by kpodemski

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

2022-01-31 20:25 UTC, matks approved these changes

2022-01-31 23:52 UTC, jolelievre approved these changes
Thanks @kpodemski

2022-01-31 23:52 UTC, jolelievre commented on ps_emailalerts.php
> +
I believe this whole function content can actually be replaced with:
```suggestion
        return Tools::getContextLocale($context);
```

2022-01-31 23:52 UTC, jolelievre commented on ps_emailalerts.php
> +
Ahhh... available as public since 177, so nevermind ^^

2022-02-01 08:40 UTC, Progi1984 requested changes
Could you bump the `config.xml` ?

2022-02-01 08:48 UTC, kpodemski commented
@Progi1984 done, thanks 👍

2022-02-01 08:49 UTC, Progi1984 approved these changes

2022-02-01 10:06 UTC, freeman78ita commented
Hi, 
after upgrade to 1.7.8.2 and upgrading to the email confirmation 2.3.1 it seems that also the order confirmations are not being sent to the client or store owner but the orders are recorded. Is this also related to the module?
Using PAYPLUG here as gateway.
All was good with 2.3.0 it seems.

2022-02-01 10:11 UTC, kpodemski commented
Hi, yes, this is a fix for this error :)

2022-02-01 10:17 UTC, freeman78ita commented
Thanks Krystian, do i have to wait for the module upgrade to fix it or act in other way? Check twitter please! I sent you a PM :)

2022-02-01 10:32 UTC, florine2623 commented
Hello @kpodemski ,

Thanks for the PR.
Now I don't have an exception anymore ✅ 
<img width="291" alt="Screenshot 2022-02-01 at 10 53 18" src="https://user-images.githubusercontent.com/16019289/151947385-5f0d34c3-0c52-448d-b7a1-0895393a520c.png">
Before :
<img width="499" alt="Screenshot 2022-02-01 at 10 53 27" src="https://user-images.githubusercontent.com/16019289/151947412-867d914d-8efa-49fa-bbb8-8f22f0b5afc1.png">

@kpodemski , is there anything else I should test ?
Rest of the features of the module work like usual.

2022-02-01 11:05 UTC, kpodemski commented
@florine2623 

It's only this single error :) in that case, we have QA ✅ ? I will create a release of the new version in the separated PR

2022-02-01 11:10 UTC, kpodemski commented
@florine2623 

Before this PR your error should look differently. Have you had the module installed before testing a new version?

2022-02-01 13:42 UTC, merged

2022-02-01 13:42 UTC, kpodemski commented
Thank you @florine2623