Fixed the hook listener for the hook actionProductAttributeDelete
PrestaShop/ps_emailalerts pull request #106
Opened 2022-02-15 13:47 UTC by Progi1984

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fixed the hook listener for the hook actionProductAttributeDelete
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Relative to PrestaShop/Prestashop#19230
| How to test?  | When the hook `actionProductAttributeDelete` is triggered, the line is now correctly removed in the table `mailalert_customer_oos`

2022-02-25 15:24 UTC, saulaski approved these changes

2022-02-28 08:30 UTC, PierreRambaud approved these changes

2022-02-28 17:24 UTC, jolelievre approved these changes
Thanks @Progi1984

2022-03-07 10:04 UTC, florine2623 requested changes
Hello @Progi1984 ,

Thanks for the PR !

Hooks `actionProductOutOfStock` & `registerGDPRConsent` are well removed ✅ 

Regarding the hook `actionProductAttributeDelete`, I don't have the same result as what you mentioned in the How to test section.

Here are the steps I followed : 
- In a combination product, add a combination A with 0 stock
- Go to product page, add your email address in the email alert section
- See a new line in table ps_mailalert_customer_oos
- Go to product sheet and delete the combination A
- Refresh your database page, line is still present in ps_mailalert_customer_oos

Could you confirm this is the wanted behavior or not ?
Thanks!

2022-03-07 15:10 UTC, Progi1984 commented
@florine2623 This hook `actionProductAttributeDelete`  is executed only when a product is removed.

2022-03-07 17:12 UTC, florine2623 approved these changes
@Progi1984,
Thanks for the details.

Indeed, now when I delete my whole product and not just an attribute of a product, the line is deleted in the database ✅ the name of the hook is a little confusing ^^

Before I delete my product :
<img width="872" alt="Screenshot 2022-03-07 at 18 09 01" src="https://user-images.githubusercontent.com/16019289/157083633-41f16187-b2d5-4026-95d0-c63e678e0ab1.png">
After I delete my product : 
<img width="868" alt="Screenshot 2022-03-07 at 18 11 12" src="https://user-images.githubusercontent.com/16019289/157083664-96e173e6-4d78-4d2a-ac81-dd587d50bf18.png">

Thanks it is QA ✅

2022-03-07 17:16 UTC, merged