Display an info alert if the customer has already subscribed.
PrestaShop/ps_emailalerts pull request #113
Opened 2022-04-11 15:52 UTC by lmeyer1

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Display an info alert if the customer has already subscribed to the product notifications.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#28218.
| How to test?  | As a customer subscribe to a product notification. Display the product page again. There is an info alert.

2022-04-12 08:43 UTC, NeOMakinG approved these changes

2022-04-14 15:20 UTC, PierreRambaud approved these changes

2022-04-22 20:17 UTC, matks reviewed
Code is OK 👍 I push a bit for behavior to be validated

2022-05-03 08:13 UTC, fabienvallon commented
LGTM

2022-05-03 08:29 UTC, Progi1984 requested changes
@lmeyer1 Could you rebase your PR, please ?

2022-05-03 09:04 UTC, lmeyer1 commented
@Progi1984 Do you mean rebase on `master`?

2022-05-03 09:18 UTC, NeOMakinG approved these changes

2022-05-04 07:36 UTC, Progi1984 approved these changes

2022-05-04 08:51 UTC, lmeyer1 commented on views/templates/hook/product.tpl
> +        <article class="mt-1 alert alert-info" role="alert">{l s='You will be notified when available' d='Modules.Emailalerts.Shop'}</article>
This looks OK to me `{l s='You will be notified when available' d='Modules.Emailalerts.Shop'}`, but when I try to translate in the back office, this string does not display for translation. Does anyone have an idea why?

2022-05-04 08:52 UTC, lmeyer1 commented on views/templates/hook/product.tpl
> +        <article class="mt-1 alert alert-info" role="alert">{l s='You will be notified when available' d='Modules.Emailalerts.Shop'}</article>
@Progi1984 @matks @NeOMakinG This looks OK to me {l s='You will be notified when available' d='Modules.Emailalerts.Shop'}, but when I try to translate in the back office, this string does not display for translation. Does anyone have an idea why?

2022-05-04 12:37 UTC, florine2623 approved these changes
Hello @lmeyer1 ,

Thanks for you PR !

Tested with branch 1.7.8.x and develop. Tested with multiple types of products.

When I am logged into my customer account, I see the info alert :
<img width="534" alt="Screenshot 2022-05-04 at 14 33 52" src="https://user-images.githubusercontent.com/16019289/166682208-af64703d-e1e8-4b10-a611-7057f117ea18.png">

When I sign out or am not logged into a customer account, I see the basic input field.

It is QA ✅

2022-05-04 12:56 UTC, merged

2022-05-04 12:56 UTC, Progi1984 commented
Thanks @lmeyer1 & @florine2623

2022-05-05 18:27 UTC, lmeyer1 commented
@Progi1984
As @Julievrz explained to me, new wordings are included in crowdin only with new major versions (1.7.8, 8.0).
Shouldn't therefore this feature be targeted to 3.0.0 and not 2.3.3? Otherwise it will show as update in current 1.7.8.x versions and the texts will not be translated.
Or am I missing something about the working of updates?