Fix product name missing
PrestaShop/ps_emailalerts pull request #74
Opened 2020-12-24 15:09 UTC by Massi-X

Don't know if you have noticed guys but the name was missing for me, patching this line fixes it.

2020-12-24 15:21 UTC, PierreRambaud requested changes
Are you able to give us a way to reproduce your issue?
Which version of PrestaShop?

2020-12-24 15:34 UTC, Massi-X commented
PrestaShop 1.7.6.8, The way to reproduce the issue is simple:
Create a product, set the availability to 0. Register for notification with a user account. Set the availability back to 1 (or anything else). Wait for the email, the name will be empty.

Moreover the product object is assigned in the line before, why not using it anyway as I've done?

2020-12-30 14:49 UTC, PierreRambaud commented
Unfortunately, I'm not able to reproduce. Could you please create an issue on the [main repository](https://github.com/PrestaShop/PrestaShop/issues/new/choose), a team will try to understand what happened to you and make sure it's reproducible

2020-12-31 10:40 UTC, hibatallahAouadni commented
Hello @PierreRambaud 

I managed to reproduce it with ps_emailalerts v2.2.1, see the attached screenshot below:

![image](https://user-images.githubusercontent.com/23308427/103404843-511b9e80-4b55-11eb-8cb0-124ee06c55ef.png)

Thanks!

2020-12-31 12:06 UTC, PierreRambaud commented
> Hello @PierreRambaud
> 
> I managed to reproduce it with ps_emailalerts v2.2.1, see the attached screenshot below:
> 
> ![image](https://user-images.githubusercontent.com/23308427/103404843-511b9e80-4b55-11eb-8cb0-124ee06c55ef.png)
> 
> Thanks!

You're talking about the Firstname & Lastname, not the product name in your screenshot :thinking:

2020-12-31 12:54 UTC, Massi-X commented
Mmh that's right, wonder if this screenshot is after applying the patch (but I don't think so). The client name is not the problem here, nor it doesn't matter to me.
To give you more informations mine is a new installation from presta 1.7.6.8 with some costum modules and no modifications to core files, so theoretically this should be the same as a test installation. Php version 7.2.33

2020-12-31 13:29 UTC, hibatallahAouadni commented
@PierreRambaud yes I'm talking about the customer name not the product cause it's the only issue I encountred.
@Massi-X I think we need to change the issue title :wink:

2020-12-31 13:43 UTC, PierreRambaud commented
> @PierreRambaud yes I'm talking about the customer name not the product cause it's the only issue I encountred.
> @Massi-X I think we need to change the issue title

I don't think we have to change the issue title, he spots a different problem than the one about the firstname and lastname, there is already an issue about this one

2020-12-31 13:52 UTC, Massi-X commented
Yeah that's right I'll try to explain better in the bug tracker [here](https://github.com/PrestaShop/PrestaShop/issues/22628)

2021-03-23 17:19 UTC, matks requested changes
Update: waiting for issue status to be confirmed https://github.com/PrestaShop/PrestaShop/issues/22628

2021-05-14 20:26 UTC, matks commented
Issue was not confirmed ⚠️ what do we do with the PR?

2021-05-14 20:31 UTC, kpodemski commented
It's wrong, this change doesn't respect product combination.

2021-05-14 22:20 UTC, Massi-X commented
Mmmh ok good point I didn't check that. So maybe the problem occurs while retrieving the name of the product with id_attribute? Needs further testing

2021-05-19 17:06 UTC, kpodemski commented
@Massi-X I remember one issue like this and it was related to corrupt structure of table related to product attributes, do you have any non-native module for products import?

2021-05-19 17:50 UTC, kpodemski commented
I can see that our QA team wasn't able to reproduce this issue, so am I, I'm closing this PR as it must be related to your installation of PrestaShop, not directly to `ps_emailalerts` module.

2021-05-19 17:50 UTC, closed without merging

2021-05-19 18:19 UTC, Massi-X commented
Nope no module for product import but I will check that table to see if there is something wrong